### PR TITLE
Breadcrumbs update for press summary

### PR DESCRIPTION
**Pull request by Donna-H**
## Changes in this PR:
Press Summary Breadcrumbs in EUI update in all views
## Trello card / Rollbar error (etc)
https://trello.com/c/ZYscYyVY/1195-eui-press-summary-breadcrumbs-in-eui
### Before
before

### After
after

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by Donna-H** [comment]
[[EUI] Press Summary Breadcrumbs in EUI](https://trello.com/c/ZYscYyVY/1195-eui-press-summary-breadcrumbs-in-eui)

**Review by Terry-Price — APPROVED** [review]
looking good Donna.

**Review by timcowlishaw — APPROVED** [review]
Great stuff, well done Donna!

**Comment by timcowlishaw** [comment]
Aha, only note is it might be worth pairing tomorrow to get those codeclimate checks passing - it's suggesting a couple of refactors that sound sensible!

**Pull request merged**
