### PR TITLE
remove checkboxes on edit page

### PR DESCRIPTION
**Pull request by Donna-H**
## Changes in this PR:
Remove checkboxes on edit page

## Trello card / Rollbar error (etc)
https://trello.com/c/y9HWdgtn/1137-eui-remove-the-three-problems-checkboxes-from-the-edit-page
### Before
before-chekboxes

### After
after-checkboxes-removed

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by Donna-H** [comment]
[EUI: Remove the three 'problems' checkboxes from the edit page](https://trello.com/c/y9HWdgtn/1137-eui-remove-the-three-problems-checkboxes-from-the-edit-page)

**Review by timcowlishaw — APPROVED** [review]

**Review by jacksonj04 — CHANGES_REQUESTED** [review]
If we're definitely losing these features, can we also remove the relevant code in the view (and probably the API and database), so we don't have dead code?

Shout up if you need a hand!

**Comment by Donna-H** [comment]
> If we're definitely losing these features, can we also remove the relevant code in the view (and probably the API and database), so we don't have dead code?
> 
> Shout up if you need a hand!

@jacksonj04 @timcowlishaw the box was only removed from edit page as per the Trello ticket a different version of the box 
 still remains in publish page and also hold page screenshots below:
after-email-block
onholdbox
published-box

**Comment by Donna-H** [comment]
@jacksonj04 @timcowlishaw  I will write up a new Trello Backend card for the API and Database and link it on Frontend card

**Review by dragon-dxw — APPROVED** [review]

**Review by jacksonj04 — APPROVED** [review]

**Pull request merged**
