### PR TITLE
Re-order Tools list lonks in More menu

### PR DESCRIPTION
**Pull request by Donna-H**
## Changes in this PR:
Re-order Tools list links in More menu
## Trello card / Rollbar error (etc)
https://trello.com/c/yf3mIF8K/1258-eui-re-order-tools-list-in-more-menu
### Before
before

### After
after

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by Donna-H** [comment]
[[EUI] Re-order Tools list in More menu](https://trello.com/c/yf3mIF8K/1258-eui-re-order-tools-list-in-more-menu)

**Review by Terry-Price — DISMISSED** [review]
@Donna-H 
Just think the line height of the list items on the more panel is a little tight.
Can you change it from 1.4rem to 1.8rem on the `<li>`s

**Comment by Donna-H** [comment]
> @Donna-H Just think the line height of the list items on the more panel is a little tight. Can you change it from 1.4rem to 1.8rem on the `<li>`s

okay done :)

**Review by anthonyhashemi — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
