### PR TITLE
Add navigation for HTML view in review page

### PR DESCRIPTION
**Pull request by Donna-H**
## Changes in this PR:
Add navigation for HTML view in review page
## Trello card / Rollbar error (etc)
https://trello.com/c/k75cnnC3/1360-eui-%E2%AC%86%E2%AC%87judgment-navigation
### Before
before-judgment
Bottom of the judgment
before-judgment-bottom

### After
after-judgment
Bottom of the judgment
after-judgment-bottom

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by Donna-H** [comment]
[[EUI] ⬆⬇Judgment navigation](https://trello.com/c/k75cnnC3/1360-eui-%E2%AC%86%E2%AC%87judgment-navigation)

**Comment by Donna-H** [comment]
[[EUI] ⬆⬇Judgment navigation](https://trello.com/c/k75cnnC3/1360-eui-%E2%AC%86%E2%AC%87judgment-navigation)

**Comment by Donna-H** [comment]
[[EUI] ⬆⬇Judgment navigation](https://trello.com/c/k75cnnC3/1360-eui-%E2%AC%86%E2%AC%87judgment-navigation)

**Review by timcowlishaw — APPROVED** [review]
Thanks Donna - this looks good to me - as we discussed I think it'd be great to pull this out of both EUI and PUI into the new shared frontend repo, but that requires a bit more thought. I'll approve this and make a new ticket for the refactor!

**Pull request merged**
