### PR TITLE
Style guide/tabs

### PR DESCRIPTION
**Pull request by Terry-Price**
## Trello card / Rollbar error (etc)
https://trello.com/c/yXaeElqW/647-eui-style-tab-switcher-for-html-pdf-view
### Before
tabs-placeholder-design

### After
tabs-component

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Review by timcowlishaw — APPROVED** [review]
Approving, but i think Nick should have the final word :-)

**Comment by timcowlishaw** [comment]
Just wanted to note, while there's JS in here, this will work fine without it too :-)

**Comment by timcowlishaw** [comment]
I would like at some point to extend this to cope with more than 2 tabs, but that can wait 'til needed. It ought to be pretty simple, just a matter of refactoring the template a little

**Review by jacksonj04 — APPROVED** [review]
Looks nice, very sharp!

**Pull request merged**
